# AUTO TAG BASED ON PUSH TO A BRANCH. AUTO RELEASE BASED ON A NON-BETA/TEST TAG.

name: Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # tag_prefix: "v"
          # tag_suffix: "b"
      - name: "🔩 Trigger next workflow"
        if: "success()"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: actions-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
